#! /usr/bin/perl

$basedir=`dirname $0`;
chop($basedir);

system "$basedir/../bin/parallel_blat $ARGV[0] $ARGV[1]";
system "$basedir/../bin/validate_contigs_blat $ARGV[0] $ARGV[1] --min_contig $ARGV[3] --similar $ARGV[2]";
